exp:
    project_name: hifigan
    exp_dir: expirement
    device: cuda
    seed: 1234
    use_wandb: true

mel:
    segment_size: 8192
    num_mels: 80
    num_freq: 1025
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    sampling_rate: 48000
    fmin: 0
    fmax: 8000
    fmax_for_loss: null

data:
    dataset: meldataset
    trainval_data_root: "VCTK"
    train_data_file_path: "VCTK/train_files.txt"
    val_data_file_path: "VCTK/val_files.txt"
    train_batch_size: 5
    val_batch_size: 5
    workers: 4

train:
    trainer: hifigan_trainer
    checkpoint_path: null
    val_metrics: []
    start_step: 1
    steps: 300
    log_step: 50
    checkpoint_step: 100
    val_step: 50

default_model:
    optimizer:
        name: adamW
        args:
            lr: 0.0002
            beta1: 0.8
            beta2: 0.99

    scheduler:
        name: exponential
        args:
            gamma: 0.99

models:
    hifigan_generator:
        inherit: default_model
        args:
            resblock: "1"
            upsample_rates: [8,8,2,2]
            upsample_kernel_sizes: [16,16,4,4]
            upsample_initial_channel: 128
            resblock_kernel_sizes: [3,7,11]
            resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
        losses:
            l1_mel_loss: 45
            hifigan_gen_loss: 1
            feature_loss: 2
    
    hifigan_mpd:
        inherit: default_model
        args: {}
        losses:
            hifigan_disc_loss: 1        
    
    hifigan_msd:
        inherit: default_model
        args: {}
        losses:
            hifigan_disc_loss: 1 
