exp:
    project_name: finally
    exp_dir: experiment
    device: cuda
    seed: 1234
    use_wandb: true
    log_batch_size: 15

mel:
    segment_size: 24576
    num_mels: 80
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    in_sr: 16000
    out_sr: 16000
    fmin: 0
    fmax: 8000
    fmax_for_loss: null

data:
    dataset: vctk-demand
    dataset_args:
        clean_wavs_dir: "clean_testset_wav"
        noisy_wavs_dir: "noisy_testset_wav"
    inference_data_root: "../vctk_demand"
    inference_data_file_path: "datasets/splits/VCTK-Demand_split/test_files.txt"
    workers: 0

inference:
    save_samples: false
    trainer: finally_stage2_trainer
    metrics: ["utmos", "dnsmos", "wv-mos", "wb_pesq", "stoi", "si_sdr"]

models:
    finally_gen:
        checkpoint_path: "/home/mabondarenko_4/course_work_baselines/experiment/checkpoints/finally_gen_checkpoint_10000_stage2_20lmos_sil8.pth"
        args: {}
    