exp:
    project_name: finally
    exp_dir: experiment
    device: cpu
    seed: 1234
    use_wandb: false
    
mel:
    segment_size: 24576
    num_mels: 80
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    in_sr: 16000
    out_sr: 48000
    fmin: 0
    fmax: 8000
    fmax_for_loss: null

data:
    dataset: finally_dataset
    dataset_args: {}
    inference_data_root: "../voxceleb"
    inference_data_file_path: null
    workers: 0

inference:
    trainer: finally_stage3_trainer
    metrics: ["utmos", "dnsmos", "wv-mos"]

models:
    finally_gen:
        checkpoint_path: "/home/mabondarenko_4/course_work_baselines/experiment/checkpoints/finally_gen_checkpoint_12000_stage3_no_hf.pth"
        args:
          use_upsamplewaveunet: true
    