exp:
    project_name: food_gan
    run_name: dcgan
    exp_dir: # exp dir
    device: cuda
    seed: 777
    use_wandb: False
    model_type: gan

data:
    dataset: # 'dataset' - for dcgan, 'labeled_dataset' - for cgan and acgan 
    num_classes: 101
    input_train_dir: # train dir
    input_val_dir: # test dir
    train_batch_size: 32
    val_batch_size: 32
    workers: 6

train:
    trainer: # dcgan_trainer or cgan_trainer or acgan_trainer
    generator: # dcgan_gen or cgan_gen or acgan_gen
    discriminator: # dcgan_disc or cgan_disc or acgan_disc
    gen_optimizer: adam
    disc_optimizer: adam
    n_disc: # amount of training loops discriminator makes in training step
    n_gen: # amount of training loops generator makes in training step
    checkpoint_path: # chp path
    val_metrics: ["fid"]
    start_step: 1
    steps: 300000
    log_step: 50
    checkpoint_step: 5000
    val_step: 1000


generator_args:
    z_dim: # size of noise vector
    emb_dim: # size of embedding vector for cgan and acgan
    num_classes: 101
    hidden_dims: [512, 256, 128, 128] # dims of convolutional layers
    activation: # relu or leaky_relu or tanh
    normalization: # batchnorm or instancenorm or layernorm

discriminator_args:
    emb_dim: # size of embedding vector for cgan and acgan
    num_classes: 101
    hidden_dims: [128, 128, 256, 512] # dims of convolutional layers
    activation: # relu or leaky_relu or tanh
    normalization: # batchnorm or instancenorm or layernorm

gen_optimizer_args:
    lr: 0.0002

disc_optimizer_args:
    lr: 0.0002

gen_losses:
    bce_gen: 1.0 # for dcgan and cgan
    ac_gen: 0.0 # for acgan

disc_losses:
    bce_disc: 1.0 # for dcgan and cgan
    ac_disc: 0.0 # for acgan
    